# Borsa İstanbul (BIST) - Endeksler ve BIST 100 Hisseleri
BIST_SYMBOLS = {
    "XU100": "BIST 100 Endeksi",
    "XU030": "BIST 30 Endeksi",
    "AEFES": "Anadolu Efes",
    "AGHOL": "AG Anadolu Grubu",
    "AHGAZ": "Ahlatcı Doğalgaz",
    "AKBNK": "Akbank",
    "AKCNS": "Akçansa",
    "AKFGY": "Akiş GYO",
    "AKSA": "Aksa Akrilik",
    "AKSEN": "Aksa Enerji",
    "ALARK": "Alarko Holding",
    "ALBRK": "Albaraka Türk",
    "ALFAS": "Alfa Solar Enerji",
    "ARCLK": "Arçelik",
    "ASELS": "Aselsan",
    "ASTOR": "Astor Enerji",
    "BERA": "Bera Holding",
    "BIMAS": "BİM Mağazalar",
    "BIOEN": "Biotrend Enerji",
    "BRSAN": "Borusan Boru",
    "BRYAT": "Borusan Yatırım",
    "BUCIM": "Bursa Çimento",
    "CANTE": "Çan2 Termik",
    "CCOLA": "Coca-Cola İçecek",
    "CEMTS": "Çemtaş",
    "CIMSA": "Çimsa",
    "CWENE": "CW Enerji",
    "DOAS": "Doğuş Otomotiv",
    "DOHOL": "Doğan Holding",
    "ECILC": "Eczacıbaşı İlaç",
    "ECZYT": "Eczacıbaşı Yatırım",
    "EGEEN": "Ege Endüstri",
    "EKGYO": "Emlak Konut GYO",
    "ENJSA": "Enerjisa",
    "ENKAI": "Enka İnşaat",
    "EREGL": "Ereğli Demir Çelik",
    "EUREN": "Europower Enerji",
    "FENER": "Fenerbahçe Futbol",
    "FROTO": "Ford Otosan",
    "GARAN": "Garanti BBVA",
    "GENIL": "Gen İlaç",
    "GESAN": "Girişim Elektrik",
    "GLYHO": "Global Yatırım Holding",
    "GUBRF": "Gübre Fabrikaları",
    "GWIND": "Galata Wind Enerji",
    "HALKB": "Halkbank",
    "HEKTS": "Hektaş",
    "IPEKE": "İpek Doğal Enerji",
    "ISCTR": "İş Bankası (C)",
    "ISDMR": "İskenderun Demir Çelik",
    "ISGYO": "İş GYO",
    "ISMEN": "İş Yatırım",
    "IZENR": "İzdemir Enerji",
    "KCAER": "Kocaer Çelik",
    "KCHOL": "Koç Holding",
    "KONTR": "Kontrolmatik",
    "KONYA": "Konya Çimento",
    "KORDS": "Kordsa",
    "KOZAA": "Koza Madencilik",
    "KOZAL": "Koza Altın",
    "KRDMD": "Kardemir (D)",
    "KZBGY": "Kızılbük GYO",
    "MAVI": "Mavi Giyim",
    "MGROS": "Migros",
    "MIATK": "Mia Teknoloji",
    "ODAS": "Odaş Elektrik",
    "OTKAR": "Otokar",
    "OYAKC": "Oyak Çimento",
    "PENTA": "Penta Teknoloji",
    "PETKM": "Petkim",
    "PGSUS": "Pegasus",
    "PSGYO": "Pasifik GYO",
    "QUAGR": "Qua Granite",
    "SAHOL": "Sabancı Holding",
    "SASA": "SASA Polyester",
    "SAYAS": "Say Yenilenebilir Enerji",
    "SDTTR": "SDT Uzay ve Savunma",
    "SISE": "Şişecam",
    "SKBNK": "Şekerbank",
    "SMRTG": "Smart Güneş Enerjisi",
    "SOKM": "Şok Marketler",
    "TAVHL": "TAV Havalimanları",
    "TCELL": "Turkcell",
    "THYAO": "Türk Hava Yolları",
    "TKFEN": "Tekfen Holding",
    "TOASO": "Tofaş",
    "TSKB": "TSKB",
    "TSPOR": "Trabzonspor",
    "TTKOM": "Türk Telekom",
    "TTRAK": "Türk Traktör",
    "TUKAS": "Tukaş",
    "TUPRS": "Tüpraş",
    "TURSG": "Türkiye Sigorta",
    "ULKER": "Ülker Bisküvi",
    "VAKBN": "Vakıfbank",
    "VESBE": "Vestel Beyaz Eşya",
    "VESTL": "Vestel",
    "YEOTK": "Yeo Teknoloji",
    "YKBNK": "Yapı Kredi",
    "YYLGD": "Yayla Gıda",
    "ZOREN": "Zorlu Enerji"
}

# Kripto Paralar (Yahoo Finance Formatında)
CRYPTO_SYMBOLS = {
    "BTC-USD": "Bitcoin",
    "ETH-USD": "Ethereum",
    "BNB-USD": "Binance Coin",
    "SOL-USD": "Solana",
    "XRP-USD": "Ripple",
    "ADA-USD": "Cardano",
    "AVAX-USD": "Avalanche",
    "DOGE-USD": "Dogecoin",
    "DOT-USD": "Polkadot",
    "MATIC-USD": "Polygon"
}

# ABD Borsaları (NASDAQ/NYSE)
US_SYMBOLS = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corp.",
    "GOOGL": "Alphabet Inc. (Google)",
    "AMZN": "Amazon.com",
    "TSLA": "Tesla Inc.",
    "NVDA": "NVIDIA Corp.",
    "META": "Meta Platforms (Facebook)",
    "NFLX": "Netflix",
    "AMD": "Advanced Micro Devices",
    "INTC": "Intel Corp."
}

# Emtia ve Döviz Kurları
COMMODITY_SYMBOLS = {
    "GC=F": "Altın (Ons)",
    "SI=F": "Gümüş (Ons)",
    "CL=F": "Ham Petrol (Crude Oil)",
    "NG=F": "Doğalgaz",
    "TRY=X": "USD/TRY (Dolar Kuru)",
    "EURTRY=X": "EUR/TRY (Euro Kuru)",
    "EURUSD=X": "EUR/USD Parite"
}